### PR TITLE
Minor improvements in the pull request template

### PR DESCRIPTION
**Pull request by Panquesito7**
# Pull Request

## Description

- Removed the `:` in headers.

### CODE REVIEW

**Comment by Akshu-on-github** [comment]
Changes made:
- Adds link to Contributing.md
- Removes the colons in the heading
The former adds value but the latter is subjective, what do you folks think?

**Comment by nhcarrigan** [comment]
I'm fine with removing the colons. Works for me either way.

For the contributing link, though - that's within a comment so doesn't render as markdown. Rather than using markdown link syntax, we should just add the bare URL.

**Comment by Akshu-on-github** [comment]
Oh, good point 🤔

**Comment by Panquesito7** [comment]
> we should just add the bare URL

Fixed. 🙂

**Review by Vyvy-vi — COMMENTED** [review]
Looks Good To Me!

**Review by Vyvy-vi — APPROVED** [review]

**Review by Akshu-on-github — APPROVED** [review]
LGTM ✅

**Comment by Akshu-on-github** [comment]
I'll merge the PR now

**Pull request merged**
