### PR TITLE
favicon added

### LINKED ISSUE #17: [FEAT] Favicon Missing
# Feature Request

## Is your feature request related to a problem? Please describe:

A favicon adds to the cleaner look of the site as well as helps in Search Engine Optimization

## Describe the solution you'd like

Update the favicon provided an image or text and shall convert it into  .ico file and add it to the website

### PR DESCRIPTION
**Pull request by AnirudhPanda**
# Pull Request

## Description:

Favicon added

## Related Issue:

Closes #17

### CODE REVIEW

**Comment by Skyhero-admin** [comment]
Looks cool,
I think a different font for the C's in the favicon would look good , But I am not sure which font 😅
That's just my opinion though.
Looks good to me anyways 👍

**Comment by AnirudhPanda** [comment]
Shall I remove the merge conflicts and create a PR again? @nhcarrigan

**Comment by nhcarrigan** [comment]
Rather than creating a new PR you can rebase this one.

**Review by nhcarrigan — APPROVED** [review]
Looks good to me.

**Review by SashoStoichkov — APPROVED** [review]
LGTM 👍🏻 Thank you for collaborating 💯

**Pull request merged**
