### PR TITLE
Updated the card styling

### PR DESCRIPTION
**Pull request by Programmer005**
# Pull Request

## Related Issue

Closes #XXXXX

### CODE REVIEW

**Comment by Panquesito7** [comment]
Could you please share a screenshot of how does it look and how it looked before? Thank you. 🙂

**Comment by Programmer005** [comment]
image
After

image
Before

**Comment by Programmer005** [comment]
image
### Before

### After
image

**Review by nhcarrigan — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Awesome work! LGTM. 🚀

**Pull request merged**
