### PR TITLE
Update Profile Photo Link

### PR DESCRIPTION
**Pull request by shreyas44**
# Pull Request

## Description

- Fixed the Profile Photo link

### CODE REVIEW

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Review by krishguptadev — COMMENTED** [review]
LGTM!

**Pull request merged**
