### PR TITLE
fix: ui issue in the rewrite branch

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
# Pull Request

## Description

Fix the UI issue in the rewrite branch and handle the responsivity.

### CODE REVIEW

**Comment by ReubenMenezes** [comment]
@nhcarrigan Is there anyway to preview this? I kinda wanna see the changes instead of viewing the diffs.

**Comment by TAKANOME-DEV** [comment]
Hey @ReubenMenezes  you can install [Gitpod](https://chrome.google.com/webstore/detail/gitpod-always-ready-to-co/dodmmooeoklaejobgleioelladacbeki/related) and open it in your browser or vscode desktop and start reviewing the changes

**Comment by ReubenMenezes** [comment]
Thanks!

**Comment by ReubenMenezes** [comment]
The styling looks great! However I've noticed that the content is the same as the old content, it was changed for a reason. Some of the links are dead, those can be removed. The calendar doesn't exist anymore so that can be removed as well. And a 
```css
body{
scroll-behavior:smooth;
```
would be nice as well.

**Comment by ReubenMenezes** [comment]
LGTM!

**Comment by ReubenMenezes** [comment]
Naomi can we get this approved please?

**Comment by ReubenMenezes** [comment]
@nhcarrigan @nhcommunity/moderators

**Comment by ReubenMenezes** [comment]
> @ReubenMenezes you can also make changes and commit it here 😉

sry,been of gh and not checking msgs.  didn't know that, thanks!

**Review by nhcarrigan — APPROVED** [review]

**Comment by nhcarrigan** [comment]
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.nhcarrigan.com)

**Pull request merged**
